# Generated by Django 4.2.5 on 2023-09-18 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон')),
                ('date', models.DateField(verbose_name='Дата')),
                ('start_time', models.TimeField(verbose_name='Начало')),
                ('end_time', models.TimeField(verbose_name='Конец')),
                ('is_available', models.BooleanField(default=True, verbose_name='Бронь')),
                ('game_master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.gamemaster')),
                ('game_system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.game')),
            ],
        ),
    ]
