# Generated by Django 4.2.5 on 2023-09-19 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_bookingtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingtime',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='bookingtime',
            name='game_master',
        ),
        migrations.RemoveField(
            model_name='bookingtime',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='bookingtime',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='gamemaster',
            name='game_systems',
        ),
        migrations.RemoveField(
            model_name='gamemaster',
            name='middle_name',
        ),
        migrations.AddField(
            model_name='bookingtime',
            name='time',
            field=models.CharField(choices=[('17:00 - 19:30', '17:00-19:30'), ('20:00 - 22:30', '20:00-22:30')], default='17:00 - 19:30', max_length=20, verbose_name='Время'),
        ),
        migrations.AddField(
            model_name='bookingtime',
            name='user_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='bookingtime',
            name='user_phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Телефон'),
        ),
    ]
