# Generated by Django 4.2.5 on 2023-09-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_bookingtime_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemaster',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='main/static/img/DM', verbose_name='Фото'),
        ),
    ]
