# Generated by Django 4.2.5 on 2023-09-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_gamemaster_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemaster',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/main/img/DM', verbose_name='Фото'),
        ),
    ]
